In [18]:
logfile = '../log_bert.csv'
logfile = '../logs_resnet50.csv'
# logfile = '../alexnet_log.csv'
logfile = '../logs_gpt2.csv'

In [19]:
import pandas as pd
import ast

# Read the file line by line and convert each line to a list using ast.literal_eval
data = []
with open(logfile, 'r') as file:
    for line in file:
        data.append(ast.literal_eval(line))

# Create a DataFrame from the list of lists with custom column names
df = pd.DataFrame(data, columns=['prediction', 'timestamp', 'prepro_time', 'predict_time', 'total_time'])

# Drop the 'prediction' column
df.drop('prediction', axis=1, inplace=True)

# Convert 'timestamp' column to datetime and extract the minute value
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['minute'] = df['timestamp'].dt.minute

# Print the DataFrame
df

                    timestamp  prepro_time  predict_time  total_time  minute
0  2023-07-29 16:35:25.805363     0.000815      1.648445    1.649260      35
1  2023-07-29 16:35:27.810460     0.001433      1.422975    1.424408      35
2  2023-07-29 16:35:29.796163     0.001469      1.436315    1.437784      35
3  2023-07-29 16:35:31.829529     0.002044      1.336280    1.338324      35
4  2023-07-29 16:35:33.906036     0.001889      1.381122    1.383011      35
5  2023-07-29 16:35:35.827499     0.001193      1.456042    1.457235      35
6  2023-07-29 16:35:37.860000     0.001457      1.357207    1.358664      35
7  2023-07-29 16:35:39.860243     0.000917      1.455624    1.456541      35
8  2023-07-29 16:35:41.858076     0.001343      1.471385    1.472728      35
9  2023-07-29 16:35:43.815737     0.001563      1.416332    1.417895      35
10 2023-07-29 16:35:45.859153     0.001696      1.377519    1.379215      35
11 2023-07-29 16:35:47.958601     0.001388      1.394491    1.395879      35
12 2023-07-29 16:35:49.995137     0.001219      1.462182    1.463401      35
13 2023-07-29 16:35:52.065896     0.001486      1.381296    1.382782      35
14 2023-07-29 16:35:54.080307     0.001268      1.517176    1.518444      35
15 2023-07-29 16:35:56.145932     0.001525      1.317752    1.319277      35
16 2023-07-29 16:35:58.099459     0.001345      1.475532    1.476877      35
17 2023-07-29 16:36:00.075801     0.001244      1.350392    1.351636      36
18 2023-07-29 16:36:02.095599     0.001267      1.485738    1.487005      36
19 2023-07-29 16:36:04.083953     0.001194      1.469626    1.470820      36
20 2023-07-29 16:36:06.134462     0.001329      1.500879    1.502208      36
21 2023-07-29 16:36:08.129950     0.001454      1.378012    1.379466      36
22 2023-07-29 16:36:10.076529     0.001497      1.289252    1.290749      36
23 2023-07-29 16:36:12.055015     0.001374      1.469823    1.471196      36
24 2023-07-29 16:36:14.029689     0.001453      1.347877    1.349330      36
25 2023-07-29 16:36:16.041754     0.001362      1.496219    1.497581      36
26 2023-07-29 16:36:17.968357     0.001438      1.334310    1.335748      36
27 2023-07-29 16:36:19.979982     0.002224      1.343511    1.345735      36
28 2023-07-29 16:36:21.945588     0.001378      1.511911    1.513289      36

In [20]:
percentiles = [0.99, 0.9, 0.5]
response_times = df['total_time'].quantile(percentiles)
response_times

0.99    1.612632
0.90    1.504424
0.50    1.424408
Name: total_time, dtype: float64